---
- name: Create user
  user:
    name: privileged
    shell: /bin/bash
    groups: sudo
    append: yes

- name: Install packages
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - curl
    - htop
    - python3
    - vim

- name: Copy service
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 755
  with_items:
    - { src: app.service.j2, dest: /lib/systemd/system/app.service }
    - { src: stress-cpu.py.j2, dest: /opt/stress-cpu.py}

- name: Enable app service
  systemd:
    name: app.service
    state: restarted
    enabled: yes
    daemon_reload: yes
